### ISSUE TITLE
Revised Galactic Plane survey priority maps

### ISSUE THREAD

**Issue by rachel3834** [lsst/rubin_sim#127]
At the request of members of TVS and SMWLV, I've revised my maps of priority regions of the Galactic Plane.  They now include updated lists of open and globular clusters and a map of X-ray binary distributions. 

The revised maps can be found [here](https://github.com/LSST-TVSSC/software_tools/tree/main/footprint_maps).  
The required filenames are priority_GalPlane_footprint_map_data_{u,g,r,i,z,y}.fits (please distinguish between these and the related map_plot files, which are not required for the metric and are included for information only).  

Please note that the format of binary table that these FITS files contain has been updated to give more flexible output from the corresponding metrics, which are also being updated, as discussed with Lynne.   The binary table now includes the priority values per HEALpix both for the full desired survey map plus the desired regions of each component science case individually.

**Comment by rachel3834** [comment]
These maps were generated using revamped code from the [LSST-TVS_software_tools repository](https://github.com/LSST-TVSSC/software_tools):
generate_sky_maps.py now produces individual HEALpix maps of the sky regions preferred by different science cases
generate_priority_maps.py combines this output into a single map data file which is read in by the Galactic Plane survey metrics.  

Both codes use the [footprint_map_config.json](https://github.com/LSST-TVSSC/software_tools/blob/main/footprint_maps/footprint_map_config.json) configuration file.

**Comment by rachel3834** [comment]
I've also generated an _alternative_ set of Galactic Plane footprint maps, which incorporate a smaller number of larger pencilbeam fields.  The motivation for this is to provide a comparison with the maps above in terms of the survey efficiency once dithering is taken into account.  
The alternative map data files are called priority_GalPlane_footprint_alt_map_data_{u,g,r,i,z,y}.fits.

**Comment by rhiannonlynne** [comment]
Added to MAF data files as of version maf_2022_1_22
