### ISSUE TITLE
Required files (catalog of nearby galaxies and simulated luminosity function) for LVDwarfsMetrics

### ISSUE THREAD

**Issue by jeffcarlin** [lsst/rubin_sim#131]
I've attached the two files that will need to be added to rubin_sim/data in order for the LVDwarfsMetrics to work. One is a simulated luminosity function for an old, metal-poor stellar population (as an ASCII table), and the other is a catalog of nearby galaxies (as a FITS file).

Please let me know if you need any further information.

Thanks-
Jeff

[LF_-1.5_10Gyr.dat.gz](https://github.com/lsst/rubin_sim/files/7867503/LF_-1.5_10Gyr.dat.gz)
[lsst_galaxies_1p25to9Mpc_table.fits.gz](https://github.com/lsst/rubin_sim/files/7867504/lsst_galaxies_1p25to9Mpc_table.fits.gz)

**Comment by rhiannonlynne** [comment]
Added to MAF data files as of version maf_2022_1_22
