### ISSUE TITLE
GalPlane priority maps updated to fix projection issue

### ISSUE THREAD

**Issue by rachel3834** [lsst/rubin_sim#151]
I've resolved an issue with the projection of pixels at large separations from the Galactic Center. 
I've also added a version string to the FITS table file header for better traceability. 
The revised map data can be found at: https://github.com/LSST-TVSSC/software_tools/tree/main/footprint_maps
Filenames: priority_GalPlane_footprint_map_{u,g,r,i,iz,y}.fits and priority_GalPlane_footprint_alt_map_{u,g,r,i,z,y}.fits

**Comment by rachel3834** [comment]
Not quite ready to update yet - I will add the precalculated coadded maps

**Comment by rachel3834** [comment]
OK, I've added precalculated maps that sum the priority of a given HEALpix over all filters for each science case.  These are included as separate files, so the full file set to include is:
priority_GalPlane_footprint_map_{u,g,r,i,iz,y}.fits and priority_GalPlane_footprint_map_data_sum.fits

and the corresponding alternative map footprints with larger pencilbeams:

priority_GalPlane_footprint_alt_map_{u,g,r,i,z,y}.fits priority_GalPlane_footprint_alt_map_data_sum.fits

These files are now ready to integrate.

**Comment by rachel3834** [comment]
Apologies, the correct filenames are:
priority_GalPlane_footprint_map_data_{u,g,r,i,iz,y}.fits and priority_GalPlane_footprint_map_data_sum.fits

and the corresponding alternative map footprints with larger pencilbeams:

priority_GalPlane_footprint_alt_map_data_{u,g,r,i,z,y}.fits priority_GalPlane_footprint_alt_map_data_sum.fits

(The PNG and *_map_plot_* files in the same directory are produced for verification purposes and are not required for the MAF itself).

**Comment by rhiannonlynne** [comment]
Added to *maps* in maps_2022_2_24 (and removed from *maf* as of maf_2022_2_24). 
This is because it's being used in MAF as an actual Map now. 
The scheduler can retrieve it from maps as well, but for general users it's probably easier to find in Maps.
