### ISSUE TITLE
GalPlane maps updated to renormalize XRB maps; add map list to FITS header

### ISSUE THREAD

**Issue by rachel3834** [lsst/rubin_sim#159]
Galactic plane maps updated as discussed:
* X-ray binary maps have been renormalized to ensure voting maps are correct
* List of science maps has been added to the FITS header for reference
* Radius of the Galactic Bulge extended

Map data can be found in [this repo](https://github.com/LSST-TVSSC/software_tools/tree/main/footprint_maps).  

Map files required are:
priority_GalPlane_footprint_map_data_{u,g,r,i,z,y}.fits  and priority_GalPlane_footprint_map_data_sum.fits
priority_GalPlane_footprint_alt_map_data_{u,g,r,i,z,y}.fits  and priority_GalPlane_footprint_alt_map_data_sum.fits

**Comment by rhiannonlynne** [comment]
Added to maps_2022_2_28
