### ISSUE TITLE
instructions missing pip install requests

### ISSUE THREAD

**Issue by fedhere** [lsst/rubin_sim#180]
I just followed the instruction to install on a new laptop - I had to add ```pip install requests'''

**Comment by rhiannonlynne** [comment]
"requests" is in the requirements.txt file and should have been installed when you set up the environment .. was there a failure at the 
`conda install -c conda-forge --file=requirements.txt` 
step?

**Comment by rhiannonlynne** [comment]
@fedhere I can't reproduce the failure, please let me know if you have further information. Otherwise I'll go ahead and close this issue in a few days.
