### ISSUE TITLE
READMEs

### ISSUE THREAD

**Issue by fedhere** [lsst/rubin_sim#244]
The original github repos (e.g. MAF) used to have useful readme files. It would be good to integrate them in the subfolders dedicated to MAF and Opsim for example

**Comment by rhiannonlynne** [comment]
Hi Fed, 
Can you clarify what you found useful about the old READMEs? I looked at the sims_maf one and found install instructions (which are in our new README, for the entire package) and a pointer on what to reference (which we could add here). 

We also have basic documentation on rubin-sim.lsst.io (linked at the sidebar of the git repo) although this is fairly rudimentary at this point. 

Lynne
