### ISSUE TITLE
setuptools_scm 8 has changed write_to to version_file

### ISSUE THREAD

**Issue by erykoff** [lsst/rubin_sim#362]
The pyproject.toml on rubin_sim uses write_to to create the version file.  But this has been changed with setuptools_scm version 8: https://github.com/pypa/setuptools_scm/blob/main/CHANGELOG.rst#v800

So the version of setuptools_scm needs to be pinned at < 8, and/or the new API needs to be used.  The rubin_sim_feedstock needs corresponding changes.

I have no idea if it's possible to support both versions at the same time.  Fun!

**Comment by rmjarvis** [comment]
They're up to 8.0.3 now.  I haven't checked whether things work with this version, but they presumably got a lot of complaints about their breaking change...

**Comment by rhiannonlynne** [comment]
I tried updating to what *should* work with version 8, and it still doesn't create a version file. 
So for now, I guess I'll stick with pinning the version.

**Comment by rhiannonlynne** [comment]
Should be resolved with https://github.com/lsst/rubin_sim/pull/364
